/*
 * ATTENTION: An "eval-source-map" devtool has been used.
 * This devtool is neither made for production nor for readable output files.
 * It uses "eval()" calls to create a separate source file with attached SourceMaps in the browser devtools.
 * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)
 * or disable the default devtool with "devtool: false".
 * If you are looking for production-ready output files, see mode: "production" (https://webpack.js.org/configuration/mode/).
 */
(self["webpackChunk"] = self["webpackChunk"] || []).push([["home-tsx"],{

/***/ "./apps/legacy/controllers lazy recursive ^\\.\\/.*$ referencedExports: default":
/*!*****************************************************************************************************************!*\
  !*** ./apps/legacy/controllers/ lazy ^\.\/.*$ referencedExports: default chunkName: [request] namespace object ***!
  \*****************************************************************************************************************/
/***/ (function(module, __unused_webpack_exports, __webpack_require__) {

var map = {
	"./edititemmetadata": [
		"./apps/legacy/controllers/edititemmetadata.js",
		[
			"edititemmetadata"
		]
	],
	"./edititemmetadata.html": [
		"./apps/legacy/controllers/edititemmetadata.html",
		[
			"edititemmetadata-html"
		]
	],
	"./edititemmetadata.js": [
		"./apps/legacy/controllers/edititemmetadata.js",
		[
			"edititemmetadata"
		]
	],
	"./favorites": [
		"./apps/legacy/controllers/favorites.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"favorites"
		]
	],
	"./favorites.js": [
		"./apps/legacy/controllers/favorites.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"favorites"
		]
	],
	"./home": [
		"./apps/legacy/controllers/home.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"lib_scroller_index_js",
			"elements_emby-scroller_emby-scroller_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"home-js",
			"home"
		]
	],
	"./home.html": [
		"./apps/legacy/controllers/home.html",
		[
			"home-html"
		]
	],
	"./home.js": [
		"./apps/legacy/controllers/home.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"lib_scroller_index_js",
			"elements_emby-scroller_emby-scroller_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"home-js"
		]
	],
	"./hometab": [
		"./apps/legacy/controllers/hometab.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_homesections_homesections_js",
			"hometab"
		]
	],
	"./hometab.js": [
		"./apps/legacy/controllers/hometab.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_homesections_homesections_js",
			"hometab"
		]
	],
	"./itemDetails": [
		"./apps/legacy/controllers/itemDetails/index.js",
		[
			"node_modules.@babel.runtime",
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"node_modules.date-fns.esm",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"itemDetails"
		]
	],
	"./itemDetails/": [
		"./apps/legacy/controllers/itemDetails/index.js",
		[
			"node_modules.@babel.runtime",
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"node_modules.date-fns.esm",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"itemDetails"
		]
	],
	"./itemDetails/index": [
		"./apps/legacy/controllers/itemDetails/index.js",
		[
			"node_modules.@babel.runtime",
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"node_modules.date-fns.esm",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"itemDetails"
		]
	],
	"./itemDetails/index.html": [
		"./apps/legacy/controllers/itemDetails/index.html",
		[
			"itemDetails-index-html"
		]
	],
	"./itemDetails/index.js": [
		"./apps/legacy/controllers/itemDetails/index.js",
		[
			"node_modules.@babel.runtime",
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"node_modules.date-fns.esm",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"itemDetails"
		]
	],
	"./list": [
		"./apps/legacy/controllers/list.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_multiSelect_multiSelect_js",
			"components_alphaPicker_alphaPicker_js",
			"list"
		]
	],
	"./list.html": [
		"./apps/legacy/controllers/list.html",
		[
			"list-html"
		]
	],
	"./list.js": [
		"./apps/legacy/controllers/list.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_multiSelect_multiSelect_js",
			"components_alphaPicker_alphaPicker_js",
			"list"
		]
	],
	"./livetv.html": [
		"./apps/legacy/controllers/livetv.html",
		[
			"livetv-html"
		]
	],
	"./livetv/livetvchannels": [
		"./apps/legacy/controllers/livetv/livetvchannels.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"livetv-livetvchannels"
		]
	],
	"./livetv/livetvchannels.js": [
		"./apps/legacy/controllers/livetv/livetvchannels.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"livetv-livetvchannels"
		]
	],
	"./livetv/livetvguide": [
		"./apps/legacy/controllers/livetv/livetvguide.js",
		[
			"components_images_imageLoader_js",
			"components_shortcuts_js",
			"lib_scroller_index_js",
			"elements_emby-scroller_emby-scroller_js",
			"elements_emby-tabs_emby-tabs_js",
			"components_guide_guide_js",
			"livetv-livetvguide"
		]
	],
	"./livetv/livetvguide.js": [
		"./apps/legacy/controllers/livetv/livetvguide.js",
		[
			"components_images_imageLoader_js",
			"components_shortcuts_js",
			"lib_scroller_index_js",
			"elements_emby-scroller_emby-scroller_js",
			"elements_emby-tabs_emby-tabs_js",
			"components_guide_guide_js",
			"livetv-livetvguide"
		]
	],
	"./livetv/livetvrecordings": [
		"./apps/legacy/controllers/livetv/livetvrecordings.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"livetv-livetvrecordings"
		]
	],
	"./livetv/livetvrecordings.js": [
		"./apps/legacy/controllers/livetv/livetvrecordings.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"livetv-livetvrecordings"
		]
	],
	"./livetv/livetvschedule": [
		"./apps/legacy/controllers/livetv/livetvschedule.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"livetv-livetvschedule"
		]
	],
	"./livetv/livetvschedule.js": [
		"./apps/legacy/controllers/livetv/livetvschedule.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"livetv-livetvschedule"
		]
	],
	"./livetv/livetvseriestimers": [
		"./apps/legacy/controllers/livetv/livetvseriestimers.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"livetv-livetvseriestimers"
		]
	],
	"./livetv/livetvseriestimers.js": [
		"./apps/legacy/controllers/livetv/livetvseriestimers.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"livetv-livetvseriestimers"
		]
	],
	"./livetv/livetvsuggested": [
		"./apps/legacy/controllers/livetv/livetvsuggested.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-tabs_emby-tabs_js",
			"livetv-livetvsuggested"
		]
	],
	"./livetv/livetvsuggested.js": [
		"./apps/legacy/controllers/livetv/livetvsuggested.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-tabs_emby-tabs_js",
			"livetv-livetvsuggested"
		]
	],
	"./lyrics": [
		"./apps/legacy/controllers/lyrics.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"lyrics"
		]
	],
	"./lyrics.html": [
		"./apps/legacy/controllers/lyrics.html",
		[
			"lyrics-html"
		]
	],
	"./lyrics.js": [
		"./apps/legacy/controllers/lyrics.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"lyrics"
		]
	],
	"./movies/moviecollections": [
		"./apps/legacy/controllers/movies/moviecollections.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_alphaPicker_alphaPicker_js",
			"movies-moviecollections"
		]
	],
	"./movies/moviecollections.js": [
		"./apps/legacy/controllers/movies/moviecollections.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_alphaPicker_alphaPicker_js",
			"movies-moviecollections"
		]
	],
	"./movies/moviegenres": [
		"./apps/legacy/controllers/movies/moviegenres.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"movies-moviegenres"
		]
	],
	"./movies/moviegenres.js": [
		"./apps/legacy/controllers/movies/moviegenres.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"movies-moviegenres"
		]
	],
	"./movies/movies": [
		"./apps/legacy/controllers/movies/movies.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"movies-movies"
		]
	],
	"./movies/movies.html": [
		"./apps/legacy/controllers/movies/movies.html",
		[
			"movies-movies-html"
		]
	],
	"./movies/movies.js": [
		"./apps/legacy/controllers/movies/movies.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"movies-movies"
		]
	],
	"./movies/moviesrecommended": [
		"./apps/legacy/controllers/movies/moviesrecommended.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"movies-moviesrecommended"
		]
	],
	"./movies/moviesrecommended.js": [
		"./apps/legacy/controllers/movies/moviesrecommended.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"movies-moviesrecommended"
		]
	],
	"./music/music.html": [
		"./apps/legacy/controllers/music/music.html",
		[
			"music-music-html"
		]
	],
	"./music/musicalbums": [
		"./apps/legacy/controllers/music/musicalbums.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"music-musicalbums"
		]
	],
	"./music/musicalbums.js": [
		"./apps/legacy/controllers/music/musicalbums.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"music-musicalbums"
		]
	],
	"./music/musicartists": [
		"./apps/legacy/controllers/music/musicartists.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"music-musicartists"
		]
	],
	"./music/musicartists.js": [
		"./apps/legacy/controllers/music/musicartists.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"music-musicartists"
		]
	],
	"./music/musicgenres": [
		"./apps/legacy/controllers/music/musicgenres.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"music-musicgenres"
		]
	],
	"./music/musicgenres.js": [
		"./apps/legacy/controllers/music/musicgenres.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"music-musicgenres"
		]
	],
	"./music/musicplaylists": [
		"./apps/legacy/controllers/music/musicplaylists.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"music-musicplaylists"
		]
	],
	"./music/musicplaylists.js": [
		"./apps/legacy/controllers/music/musicplaylists.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"music-musicplaylists"
		]
	],
	"./music/musicrecommended": [
		"./apps/legacy/controllers/music/musicrecommended.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"music-musicrecommended"
		]
	],
	"./music/musicrecommended.js": [
		"./apps/legacy/controllers/music/musicrecommended.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"music-musicrecommended"
		]
	],
	"./music/songs": [
		"./apps/legacy/controllers/music/songs.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"music-songs"
		]
	],
	"./music/songs.js": [
		"./apps/legacy/controllers/music/songs.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"music-songs"
		]
	],
	"./playback/queue": [
		"./apps/legacy/controllers/playback/queue/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-queue"
		]
	],
	"./playback/queue/": [
		"./apps/legacy/controllers/playback/queue/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-queue"
		]
	],
	"./playback/queue/index": [
		"./apps/legacy/controllers/playback/queue/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-queue"
		]
	],
	"./playback/queue/index.html": [
		"./apps/legacy/controllers/playback/queue/index.html",
		[
			"playback-queue-index-html"
		]
	],
	"./playback/queue/index.js": [
		"./apps/legacy/controllers/playback/queue/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"components_itemContextMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-queue"
		]
	],
	"./playback/video": [
		"./apps/legacy/controllers/playback/video/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_mediainfo_mediainfo_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-video"
		]
	],
	"./playback/video/": [
		"./apps/legacy/controllers/playback/video/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_mediainfo_mediainfo_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-video"
		]
	],
	"./playback/video/index": [
		"./apps/legacy/controllers/playback/video/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_mediainfo_mediainfo_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-video"
		]
	],
	"./playback/video/index.html": [
		"./apps/legacy/controllers/playback/video/index.html",
		[
			"playback-video-index-html"
		]
	],
	"./playback/video/index.js": [
		"./apps/legacy/controllers/playback/video/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.headroom.js",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_mediainfo_mediainfo_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"elements_emby-slider_emby-slider_js",
			"playback-video"
		]
	],
	"./session/addServer": [
		"./apps/legacy/controllers/session/addServer/index.js",
		[
			"session-addServer"
		]
	],
	"./session/addServer/": [
		"./apps/legacy/controllers/session/addServer/index.js",
		[
			"session-addServer"
		]
	],
	"./session/addServer/index": [
		"./apps/legacy/controllers/session/addServer/index.js",
		[
			"session-addServer"
		]
	],
	"./session/addServer/index.html": [
		"./apps/legacy/controllers/session/addServer/index.html",
		[
			"session-addServer-index-html"
		]
	],
	"./session/addServer/index.js": [
		"./apps/legacy/controllers/session/addServer/index.js",
		[
			"session-addServer"
		]
	],
	"./session/login": [
		"./apps/legacy/controllers/session/login/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-login"
		]
	],
	"./session/login/": [
		"./apps/legacy/controllers/session/login/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-login"
		]
	],
	"./session/login/index": [
		"./apps/legacy/controllers/session/login/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-login"
		]
	],
	"./session/login/index.html": [
		"./apps/legacy/controllers/session/login/index.html",
		[
			"session-login-index-html"
		]
	],
	"./session/login/index.js": [
		"./apps/legacy/controllers/session/login/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"node_modules.headroom.js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-login"
		]
	],
	"./session/login/login.scss": [
		"./apps/legacy/controllers/session/login/login.scss",
		[
			"session-login-login-scss"
		]
	],
	"./session/resetPassword": [
		"./apps/legacy/controllers/session/resetPassword/index.js",
		[
			"session-resetPassword"
		]
	],
	"./session/resetPassword/": [
		"./apps/legacy/controllers/session/resetPassword/index.js",
		[
			"session-resetPassword"
		]
	],
	"./session/resetPassword/index": [
		"./apps/legacy/controllers/session/resetPassword/index.js",
		[
			"session-resetPassword"
		]
	],
	"./session/resetPassword/index.html": [
		"./apps/legacy/controllers/session/resetPassword/index.html",
		[
			"session-resetPassword-index-html"
		]
	],
	"./session/resetPassword/index.js": [
		"./apps/legacy/controllers/session/resetPassword/index.js",
		[
			"session-resetPassword"
		]
	],
	"./session/selectServer": [
		"./apps/legacy/controllers/session/selectServer/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-selectServer"
		]
	],
	"./session/selectServer/": [
		"./apps/legacy/controllers/session/selectServer/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-selectServer"
		]
	],
	"./session/selectServer/index": [
		"./apps/legacy/controllers/session/selectServer/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-selectServer"
		]
	],
	"./session/selectServer/index.html": [
		"./apps/legacy/controllers/session/selectServer/index.html",
		[
			"session-selectServer-index-html"
		]
	],
	"./session/selectServer/index.js": [
		"./apps/legacy/controllers/session/selectServer/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"session-selectServer"
		]
	],
	"./shows/episodes": [
		"./apps/legacy/controllers/shows/episodes.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"shows-episodes"
		]
	],
	"./shows/episodes.js": [
		"./apps/legacy/controllers/shows/episodes.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"shows-episodes"
		]
	],
	"./shows/tvgenres": [
		"./apps/legacy/controllers/shows/tvgenres.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"shows-tvgenres"
		]
	],
	"./shows/tvgenres.js": [
		"./apps/legacy/controllers/shows/tvgenres.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"shows-tvgenres"
		]
	],
	"./shows/tvrecommended": [
		"./apps/legacy/controllers/shows/tvrecommended.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"shows-tvrecommended"
		]
	],
	"./shows/tvrecommended.html": [
		"./apps/legacy/controllers/shows/tvrecommended.html",
		[
			"shows-tvrecommended-html"
		]
	],
	"./shows/tvrecommended.js": [
		"./apps/legacy/controllers/shows/tvrecommended.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.headroom.js",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-tabs_emby-tabs_js",
			"syncPlay-ui-settings-SettingsEditor",
			"syncPlay-ui-groupSelectionMenu",
			"scripts_libraryMenu_js",
			"shows-tvrecommended"
		]
	],
	"./shows/tvshows": [
		"./apps/legacy/controllers/shows/tvshows.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"shows-tvshows"
		]
	],
	"./shows/tvshows.js": [
		"./apps/legacy/controllers/shows/tvshows.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"node_modules.markdown-it",
			"node_modules.entities",
			"node_modules.linkify-it",
			"node_modules.punycode.js",
			"node_modules.mdurl",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"components_mediainfo_mediainfo_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"components_alphaPicker_style_scss",
			"components_listview_listview_js-node_modules_uc_micro_index_mjs",
			"components_filterdialog_filterIndicator_js-scripts_libraryBrowser_js",
			"components_alphaPicker_alphaPicker_js",
			"shows-tvshows"
		]
	],
	"./shows/tvstudios": [
		"./apps/legacy/controllers/shows/tvstudios.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"shows-tvstudios"
		]
	],
	"./shows/tvstudios.js": [
		"./apps/legacy/controllers/shows/tvstudios.js",
		[
			"node_modules.@jellyfin.sdk",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"shows-tvstudios"
		]
	],
	"./shows/tvupcoming": [
		"./apps/legacy/controllers/shows/tvupcoming.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"shows-tvupcoming"
		]
	],
	"./shows/tvupcoming.js": [
		"./apps/legacy/controllers/shows/tvupcoming.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"components_shortcuts_js",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"shows-tvupcoming"
		]
	],
	"./user/controls": [
		"./apps/legacy/controllers/user/controls/index.js",
		[
			"user-controls"
		]
	],
	"./user/controls/": [
		"./apps/legacy/controllers/user/controls/index.js",
		[
			"user-controls"
		]
	],
	"./user/controls/index": [
		"./apps/legacy/controllers/user/controls/index.js",
		[
			"user-controls"
		]
	],
	"./user/controls/index.html": [
		"./apps/legacy/controllers/user/controls/index.html",
		[
			"user-controls-index-html"
		]
	],
	"./user/controls/index.js": [
		"./apps/legacy/controllers/user/controls/index.js",
		[
			"user-controls"
		]
	],
	"./user/display": [
		"./apps/legacy/controllers/user/display/index.js",
		[
			"node_modules.@mui.material",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-display-index-tsx",
			"user-display"
		]
	],
	"./user/display/": [
		"./apps/legacy/controllers/user/display/index.js",
		[
			"node_modules.@mui.material",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-display-index-tsx",
			"user-display"
		]
	],
	"./user/display/index": [
		"./apps/legacy/controllers/user/display/index.js",
		[
			"node_modules.@mui.material",
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-display-index-tsx",
			"user-display"
		]
	],
	"./user/display/index.html": [
		"./apps/legacy/controllers/user/display/index.html",
		[
			"user-display-index-html"
		]
	],
	"./user/display/index.js": [
		"./apps/legacy/controllers/user/display/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-display",
			"user-display-index-js"
		]
	],
	"./user/home": [
		"./apps/legacy/controllers/user/home/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_homesections_homesections_js",
			"user-home"
		]
	],
	"./user/home/": [
		"./apps/legacy/controllers/user/home/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_homesections_homesections_js",
			"user-home"
		]
	],
	"./user/home/index": [
		"./apps/legacy/controllers/user/home/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_homesections_homesections_js",
			"user-home"
		]
	],
	"./user/home/index.html": [
		"./apps/legacy/controllers/user/home/index.html",
		[
			"user-home-index-html"
		]
	],
	"./user/home/index.js": [
		"./apps/legacy/controllers/user/home/index.js",
		[
			"node_modules.@jellyfin.sdk",
			"node_modules.sortablejs",
			"components_images_imageLoader_js",
			"components_cardbuilder_utils_builder_ts",
			"elements_emby-select_emby-select_js",
			"components_shortcuts_js",
			"components_actionSheet_actionSheet_ts",
			"components_indicators_indicators_js-components_guide_programs_scss",
			"components_cardbuilder_cardBuilder_js",
			"lib_scroller_index_js",
			"elements_emby-itemscontainer_emby-itemscontainer_js",
			"elements_emby-scroller_emby-scroller_js",
			"components_homesections_homesections_js",
			"user-home"
		]
	],
	"./user/playback": [
		"./apps/legacy/controllers/user/playback/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-playback"
		]
	],
	"./user/playback/": [
		"./apps/legacy/controllers/user/playback/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-playback"
		]
	],
	"./user/playback/index": [
		"./apps/legacy/controllers/user/playback/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-playback"
		]
	],
	"./user/playback/index.html": [
		"./apps/legacy/controllers/user/playback/index.html",
		[
			"user-playback-index-html"
		]
	],
	"./user/playback/index.js": [
		"./apps/legacy/controllers/user/playback/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"user-playback"
		]
	],
	"./user/subtitles": [
		"./apps/legacy/controllers/user/subtitles/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"elements_emby-slider_emby-slider_js",
			"user-subtitles"
		]
	],
	"./user/subtitles/": [
		"./apps/legacy/controllers/user/subtitles/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"elements_emby-slider_emby-slider_js",
			"user-subtitles"
		]
	],
	"./user/subtitles/index": [
		"./apps/legacy/controllers/user/subtitles/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"elements_emby-slider_emby-slider_js",
			"user-subtitles"
		]
	],
	"./user/subtitles/index.html": [
		"./apps/legacy/controllers/user/subtitles/index.html",
		[
			"user-subtitles-index-html"
		]
	],
	"./user/subtitles/index.js": [
		"./apps/legacy/controllers/user/subtitles/index.js",
		[
			"elements_emby-select_emby-select_js",
			"components_actionSheet_actionSheet_ts",
			"elements_emby-slider_emby-slider_js",
			"user-subtitles"
		]
	]
};
function webpackAsyncContext(req) {
	try {
		if(!__webpack_require__.o(map, req)) {
			return Promise.resolve().then(function() {
	var e = new Error("Cannot find module '" + req + "'");
	e.code = 'MODULE_NOT_FOUND';
	throw e;
});
		}
	} catch(err) {
		return Promise.reject(err);
	}

	var ids = map[req], id = ids[0];
	return Promise.all(ids[1].map(__webpack_require__.e)).then(function() { return __webpack_require__(id); });
}
webpackAsyncContext.keys = function() { return Object.keys(map); };
webpackAsyncContext.id = "./apps/legacy/controllers lazy recursive ^\\.\\/.*$ referencedExports: default";
module.exports = webpackAsyncContext;

/***/ })

}]);